// <auto-generated/>
using C4PlusSharp.Elements;
using C4PlusSharp.Elements.Interfaces;
using C4PlusSharp.Elements.Relationships;

namespace dotnet.eShop.Architecture.SoftwareSystems
{
    public partial class BasketApi
    {
        public partial class Containers
        {
            public partial class Data
            {
                public partial class Components
                {
                    public partial class RedisDatabase
                    {
                        public partial class Interfaces
                        {
                            public partial class StringSetAsync : IInterfaceInstance
                            {
                                public const string ALIAS = "dotnet.eShop.Architecture.SoftwareSystems.BasketApi.Containers.Data.Components.RedisDatabase.Interfaces.StringSetAsync";
                                public static Interface Instance => new Interface(dotnet.eShop.Architecture.SoftwareSystems.BasketApi.Containers.Data.Components.RedisDatabase.ALIAS, ALIAS, "String Set Async")
                                {Description = "", Path = "", IsPrivate = false, Protocol = "", Flow = new Flow(ALIAS), Input = "", InputTemplate = "", Output = "", OutputTemplate = ""};
                            }
                        }
                    }
                }
            }
        }
    }
}