// <auto-generated/>
using C4PlusSharp.Elements;
using C4PlusSharp.Elements.Interfaces;
using C4PlusSharp.Elements.Relationships;

namespace dotnet.eShop.Architecture.SoftwareSystems
{
    public partial class BasketApi : ISoftwareSystemInstance
    {
        public const string ALIAS = "dotnet.eShop.Architecture.SoftwareSystems.BasketApi";
        public static SoftwareSystem Instance => new SoftwareSystem(ALIAS, "Basket Api")
        {Description = "", Boundary = Boundary.Internal};
        public partial class Containers
        {
        }

        public partial class Interfaces
        {
        }
    }
}