// <auto-generated/>
using C4PlusSharp.Elements;
using C4PlusSharp.Elements.Interfaces;
using C4PlusSharp.Elements.Relationships;

namespace dotnet.eShop.Architecture.SoftwareSystems
{
    public partial class CatalogApi : ISoftwareSystemInstance
    {
        public const string ALIAS = "dotnet.eShop.Architecture.SoftwareSystems.CatalogApi";
        public static SoftwareSystem Instance => new SoftwareSystem(ALIAS, "Catalog Api")
        {
            Description = "",
            Boundary = Boundary.Internal
        };

        public partial class Containers
        {
        }

        public partial class Interfaces
        {
        }
    }
}