// <auto-generated/>
using C4InterFlow.Structures;
using C4InterFlow.Structures.Interfaces;

namespace DotNetEShop.SoftwareSystems
{
    public partial class BasketApi
    {
        public partial class Containers
        {
            public partial class Grpc : IContainerInstance
            {
                private static readonly string ALIAS = "DotNetEShop.SoftwareSystems.BasketApi.Containers.Grpc";
                public static Container Instance => new Container(DotNetEShop.SoftwareSystems.BasketApi.ALIAS, ALIAS, "Grpc")
                {
                    ContainerType = ContainerType.None,
                    Description = "",
                    Technology = "",
                    Boundary = Boundary.Internal
                };

                public partial class Components
                {
                }

                public partial class Interfaces
                {
                }

                public partial class Entities
                {
                }
            }
        }
    }
}