// <auto-generated/>
using C4InterFlow.Structures;
using C4InterFlow.Structures.Interfaces;

namespace dotnet.eShop.Architecture.SoftwareSystems
{
    public partial class BasketApi
    {
        public partial class Containers
        {
            public partial class Data : IContainerInstance
            {
                private static readonly string ALIAS = "dotnet.eShop.Architecture.SoftwareSystems.BasketApi.Containers.Data";
                public static Container Instance => new Container(dotnet.eShop.Architecture.SoftwareSystems.BasketApi.ALIAS, ALIAS, "Data")
                {
                    ContainerType = ContainerType.None,
                    Description = "",
                    Technology = "",
                    Boundary = Boundary.Internal
                };

                public partial class Components
                {
                }

                public partial class Interfaces
                {
                }

                public partial class Entities
                {
                }
            }
        }
    }
}