// <auto-generated/>
using C4InterFlow.Structures;
using C4InterFlow.Structures.Interfaces;

namespace DotNetEShop.SoftwareSystems
{
    public partial class CatalogApi
    {
        public partial class Containers
        {
            public partial class Api
            {
                public partial class Components
                {
                    public partial class CatalogApi : IComponentInstance
                    {
                        private static readonly string ALIAS = "DotNetEShop.SoftwareSystems.CatalogApi.Containers.Api.Components.CatalogApi";
                        public static Component Instance => new Component(DotNetEShop.SoftwareSystems.CatalogApi.Containers.Api.ALIAS, ALIAS, "Catalog Api")
                        {
                            ComponentType = ComponentType.None,
                            Description = "",
                            Technology = ""
                        };

                        public partial class Interfaces
                        {
                        }
                    }
                }
            }
        }
    }
}