// <auto-generated/>
using C4InterFlow.Structures;
using C4InterFlow.Structures.Interfaces;

namespace dotnet.eShop.Architecture.SoftwareSystems
{
    public partial class BasketApi : ISoftwareSystemInstance
    {
        private static readonly string ALIAS = "dotnet.eShop.Architecture.SoftwareSystems.BasketApi";
        public static SoftwareSystem Instance => new SoftwareSystem(ALIAS, "Basket Api")
        {
            Description = "",
            Boundary = Boundary.Internal
        };

        public partial class Containers
        {
        }

        public partial class Interfaces
        {
        }
    }
}