@startuml
object "Namespace" as Namespace
object "Software System" as SoftwareSystem 
object "Container" as Container
object "Component" as Component
object "Interface" as Interface
object "Flow" as Flow
object "Business Process" as BusinessProcess
object "Activity" as Activity
object "Actor" as Actor

enum "Flow Type" as FlowType {
    None
If
ElseIf
Else
Loop
Group
Try
Catch
Finally
ThrowException
Return
Use
}


Namespace --> SoftwareSystem : "  Has One or More"
Namespace --> Namespace : "  Has Zero or More"
SoftwareSystem --> Container: "  Has Zero or More"
Container--> Component: "  Has Zero or More"
SoftwareSystem -right-> Interface: "  Has Zero or More"
Container -right-> Interface: "  Has Zero or More"
Component -right-> Interface: "  Has Zero or More"
Interface --> Flow: "  Has Zero or More"
Flow --> Flow: "  Has Zero or More"
BusinessProcess -up-> Activity : "  Has One or More"
Activity -up-> Flow: "  Has One"
Actor -right-> Activity : "  Performs One or More"
Flow -up-> Interface : "  Uses Zero or More"
Flow -left-> FlowType : "  Can be of type"
@enduml