using System.CommandLine;

namespace C4InterFlow.Cli.Commands.Options;

public static class DiagramFormatsOption
{
    private const string PUML = "puml";
    public const string SVG = "svg";
    public const string PNG = "png";
    public const string MD = "md";
    public static Option<string[]> Get()
    {
        const string description =
           $"Diagram format(s) to draw. NOTE: Diagram(s) in '{PUML}' format are always generated by default. '{SVG}', '{PNG}' and '{MD}'arguments can be used for '{DiagramTypesOption.C4_STATIC}' and '{DiagramTypesOption.C4}' diagram types only.";

        var option = new Option<string[]>(new[] { "--formats", "-f" }, description)
        {
            IsRequired = false,
            AllowMultipleArgumentsPerToken = true
        };

        option.FromAmong(SVG, PNG, MD);

        return option;
    }
}
