using System.CommandLine;

namespace C4InterFlow.Cli.Commands.Options;

public static class FileExtensionOption
{
    public static Option<string> Get()
    {
        const string description =
           $"The file extension of the artifact used/generated by the command";

        var option = new Option<string>(new[] { "--file-extension", "-fe" }, description);

        return option;
    }
}
