// <auto-generated/>
using C4InterFlow;
using C4InterFlow.Structures;
using C4InterFlow.Structures.Interfaces;

namespace DotNetEShop.SoftwareSystems
{
    public partial class CatalogApi
    {
        public partial class Containers
        {
            public partial class Api
            {
                public partial class Components
                {
                    public partial class CatalogApi
                    {
                        public partial class Interfaces
                        {
                            public partial class GetItemById : IInterfaceInstance
                            {
                                public static Interface Instance => new Interface(Utils.GetStructureAlias<GetItemById>(), "Get Item By Id")
                                {
                                    Description = "",
                                    Path = "",
                                    IsPrivate = false,
                                    Protocol = "",
                                    Flow = new Flow(Utils.GetStructureAlias<GetItemById>())
                                    	.If(@"id <= 0")
                                    		.Return(@"TypedResults.BadRequest")
                                    	.EndIf()
                                    	.If(@"item == null")
                                    		.Return(@"TypedResults.NotFound")
                                    	.EndIf()
                                    	.Return(@"TypedResults.Ok"),
                                    Input = "",
                                    InputTemplate = "",
                                    Output = "",
                                    OutputTemplate = ""
                                };
                            }
                        }
                    }
                }
            }
        }
    }
}